apiVersion: v1
kind: Pod
metadata:
  name: gobgp
  labels:
    app: gobgp-porter
spec:
  containers:
    - name: gobgp
      image: duanjiong/gobgp:latest
      ports:
        - containerPort: 17900
      command:
        - /usr/local/bin/gobgpd
      args:
          - --api-hosts=:50052
  hostNetwork: true



